### ISSUE TITLE
how to compile this project?

### ISSUE THREAD

**Issue by psw7420** [beraldofilippo/android-hpe#6]
hello, i have compile OpenCV Library and made 2 type of headpose.so file, also i moved it to dlib folder in jniLibs

but i don`t know how can i make app-debug.apk file or run this project,
i have tried run it by android-studio and makefile, but there are so many error about gradle, 
even i have changed my gradle many times, but it still can be not solved.

so, i want to know how to compile this promgram on your envirenment. 
android studio or makefile by gradlew ?
or whats version of gradle you comfile

**Comment by beraldofilippo** [comment]
Hello,

thanks for the heads up.
I have now cleaned up and updated the project to run with AS 4.0.0, gradle 4.0.1 and androidX.
You should be able to compile and run it.
