### ISSUE TITLE
Please help to get it running...

### ISSUE THREAD

**Issue by migri1024** [beraldofilippo/android-hpe#7]
Hi!
This app looks really cool and I want to get it running and use it. However, even after many hours I don't get it  working :-( 
Sorry I am a beginner in android programming, so please excuse silly questions.

Here is what I did so far:
- I am using Android Studio 4.1.2 on a windows 10 Intel x86 64 bit laptop 
- Testing on Samsung Galaxy S10e (SM-G970F/DS) using Andoid 11
- I donwloaded your "android-hpe-master" files
- I downloaded OpenCV 4.1.2. 
- I opened your project "android-hpe-master" in Android Studio.
- I imported OpenCV using File > New> Import Module, selected the "sdk" folder in the openCV downloaded folder and named it ":opencv"
- modified "compileSdkVersion" and "targetSdkVersion" in the openCV gradle script from 26 to 29 (as is in the app gradle script)
- Set dependencies: "app" depends on "dlib"; "dlib" depends on  "opencv"; "opencv" has no dependencies
- Copied folder "\android-hpe-master\opencv\native\libs"  to "\android-hpe-master\dlib\src\main\" and renamed it as "jniLibs"
- Built project successfully with 3 warnings
- When I run the app I get error: "*More than one file was found with OS independent path 'lib/x86_64/libopencv_java4.so'.* "
- Now I tried the following: Deleted folder "libs" in "\android-hpe-master\opencv\native". When I run the app I don't get the error above! The app starts. I can see the MainActivity Screen. I click on "LAUNCH". Very shortly, I can see the next Activity, but then the app crashes. Error: "*No implementation found for int com.beraldo.hpe.dlib.HeadPoseDetector.jniInit*".
- Now I have tried a hundred things but nothing helps. 

Can you tell me how to proceed? Any help highly appreciated.
![Zwischenablage04](https://user-images.githubusercontent.com/82339059/114320359-ed225200-9b15-11eb-8dc5-6a4bfc57d753.jpg)
[Errorlog.txt](https://github.com/beraldofilippo/android-hpe/files/6292726/Errorlog.txt)

**Comment by migri1024** [comment]
Can anyone help?

**Comment by beraldofilippo** [comment]
Sorry I did not have time to have a proper look. I think you got it wrong around the setup of the build. There is no need to import any other module or alter this project dependencies structure.

First you need to get https://github.com/beraldofilippo/android-hpe-library, download the folders needed and run the command to compile the `.so` files.
Then you can start working on this project, copying the `.so` files where suggested and try to get it running.

I hope it helps.

**Comment by migri1024** [comment]
Unfortunately I am having trouble to get the compilation of hpe-library done, (see [issue](https://github.com/beraldofilippo/android-hpe-library/issues/3) if anyone wants to help).
But:
Is it not possible to simply share the library as a` .so` file?

Thanks for your help.

**Comment by migri1024** [comment]
**YEEEAH got it running**. Finally succeeded in generating the `.so` files of the hpe-library and now hpe is running ;-)

If someone else tries this using a similar configuration, maybe you have the same problems, 

1) _Failed to create main directory in /storage/emulated/0/HeadPoseEstimation_
--> add `android:requestLegacyExternalStorage="true"` to manifest, in the application section

2) _No implementation found for int com.beraldo.hpe.dlib.HeadPoseDetector.jniInit_
--> test on device, not on emulator

3) _Unable to add window android.view.ViewRootImpl$W@d141857 -- permission denied for window type 2003_
--> modify FloatingCameraWindow.java
        //mWindowParam.type = WindowManager.LayoutParams.TYPE_SYSTEM_ALERT; 
        mWindowParam.type = WindowManager.LayoutParams.TYPE_APPLICATION_OVER

**Thanks Filippo, your project is awesome!!**

**Comment by lixiangbin** [comment]
I encountered the same problem as you. I failed. Can you share or upload your XXX file? Thank you very much!

**Comment by lixiangbin** [comment]
I encountered the same problem as you. I failed. Can you share or upload your .so file? Thank you very much!

**Comment by lixiangbin** [comment]
I have the same problem as you. I failed. Can I share or upload your project(or .so file)? Thank you very much!

**Comment by lixiangbin** [comment]
I have the same problem as you. Can you share or upload your project(or .so files)? Thank you very much!

**Comment by migri1024** [comment]
Hi, sorry I am afraid it is too long ago. I would have to get into the project again myself first. Sure you tried the steps above?
May I suggest you post your errors and one of the experts here can help?
Kind regards, Michael
